
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Address      <small><?= cclang('detail', ['Address']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/address'); ?>">Address</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Address</h3>
                     <h5 class="widget-user-desc">Detail Address</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_address" id="form_address" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($address->id); ?>
                        </div>
                    </div>
                                        
                  <h3>hiji</h3>
                  <section>
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Country Id </label>

                        <div class="col-sm-8">
                           <?= _ent($address->country_id); ?>
                        </div>
                    </div>
                                        </section>
                  <h3>dua</h3>
                  <section>
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">State Id </label>

                        <div class="col-sm-8">
                           <?= _ent($address->state_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Label </label>

                        <div class="col-sm-8">
                           <?= _ent($address->label); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">City Id </label>

                        <div class="col-sm-8">
                           <?= _ent($address->city_id); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                                               </section>
                        <div class="message"></div>
                          
                    <div class="view-nav">
                        <?php is_allowed('address_update', function() use ($address){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit address (Ctrl+e)" href="<?= site_url('administrator/address/edit/'.$address->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Address']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/address/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Address']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   $('.container-button-bottom').hide();
   $('.form-step').steps({
      headerTag: 'h3',
      bodyTag: 'section',
      autoFocus: true,
      enableAllSteps : true,
      onFinishing : function(){
        $('.btn_save_back').trigger('click')
      },
      labels : {
        finish : 'save'
      },
      enableFinishButton : false
  });
  });
</script>