<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+e', function assets() {
         $('#btn_edit').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#btn_back').trigger('click');
         return false;
      });

   }


   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Notification <small><?= cclang('detail', ['Notification']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a href="<?= site_url('administrator/notification'); ?>">Notification</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">

                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Notification</h3>
                     <h5 class="widget-user-desc">Detail Notification</h5>
                     <hr>
                  </div>


                  <div class="form-horizontal form-step" name="form_notification" id="form_notification">


                     <div class="form-group ">
                        <label for="content" class="col-md-12"> </label>

                        <div class="col-sm-8">
                           <span class="detail_group-title"><?= _ent($notification->title); ?></span>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-md-12">Content </label>

                        <div class="col-sm-8">
                           <span class="detail_group-content"><?= ($notification->content); ?></span>
                        </div>
                     </div>

                     <div class="form-group ">
                        <label for="content" class="col-md-12"> </label>

                        <div class="col-sm-8">
                           <?php if ($notification->url) : ?>
                              <a class="btn btn-xs btn-flat btn-primary btn_action" id="btn_back" href="<?= $notification->url ?>"><i class="fa fa-anchor"></i> Go to URL</a>
                           <?php endif ?>
                        </div>
                     </div>

                     <br>
                     <br>




                     <div class="view-nav">


                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/notification/'); ?>"><i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Notification']); ?></a>
                     </div>

                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
   $(document).ready(function() {
      (function() {
         var title = $('.detail_group-title');
         var content = $('.detail_group-content');
         var read = $('.detail_group-read');
      })()

   });
</script>